### model
model_name_or_path: mistralai/Mixtral-8x7B-v0.1

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 16 
lora_dropout: 0

flash_attn: auto


### input
include_num_input_tokens_seen: True


### dataset
dataset: hupd_demo
template: mistral
cutoff_len: 10000
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
quantization_bit: 4 
quantization_method: bitsandbytes
## Scaling Required since the context is big
rope_scaling: linear

### output
output_dir: saves/mixtral-8x7b/lora/sft-hupd
logging_steps: 5
save_steps: 100
warmup_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
max_grad_norm: 1.0
num_train_epochs: 3.0
lr_scheduler_type: cosine
optim: adamw_torch
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500


## Reporting 
report_to: wandb
run_name: factory-mixtral-hupd-demo